version: '3.8'

services:
  yelpcamp-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # impede que o node_modules de fora sobrescreva
    command: npm run dev
